Training:
  TASK_ID: 'PickNet_S_'
  gpu_id: '3'
  batchsize: 16
  lr: 0.0003
  # opt: 'adam'
  opt: 'adam'
  # loss: 'BCE','CB_BCE', or 'Focal_CB_BCE'
  loss: 'CB_BCE'
  batch_size: 16
  STEAD_batch_size: 0
  INSTANCE_batch_size: 16 
  Noise_batch_size: 0
  Empty_batch_size: 0
  shift_max: 500
  epochs: 10
  steps_per_epoch: 10000
  validation_steps: 1000
  num_works: 16
  max_queue: 16
  filepath: './trained_models/'
  histpath: './trained_models/'

  train_log_dir: './logs/'
  use_previous_model_as_start: False
  previous_model_path: None

  STEAD_hdf5_path_train: '/mnt/GPT_disk/DL_datasets/STEAD/waveforms.hdf5'
  INSTANCE_ev_hdf5_path_train: '/mnt/GPT_disk/DL_datasets/INSTANCE/Instance_events_counts.hdf5'

  STEAD_ev_csv_path_train: '/mnt/GPT_disk/DL_datasets/STEAD/metadata_eq.csv.train.csv'
  STEAD_noise_csv_path_train: '/mnt/GPT_disk/DL_datasets/STEAD/metadata_no.csv'
  INSTANCE_ev_csv_path_train: '/mnt/GPT_disk/DL_datasets/INSTANCE/metadata_Instance_events_both_p_s.csv.train.csv'

  STEAD_ev_csv_path_val: '/mnt/GPT_disk/DL_datasets/STEAD/metadata_eq.csv.val.csv'
  INSTANCE_ev_csv_path_val: '/mnt/GPT_disk/DL_datasets/INSTANCE/metadata_Instance_events_both_p_s.csv.val.csv'

PickNet:
  wave_type: 'S'
  duplicate_num: 14
  length: 1600
  channel_num: 2
  b1_convw: 32
  b2_convw: 16
  b3_convw: 8
  b4_convw: 4
  b5_convw: 2